[build]
command = "npm run build:client"
functions = "netlify/functions"
publish = "dist/spa"


[functions]
external_node_modules = ["express", "stripe", "@supabase/supabase-js"]
node_bundler = "esbuild"

# Hourly reminders + expiry warnings
[[scheduled.functions]]
name = "send-reminders"
schedule = "@hourly"

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"
